env: # Environt variable to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone repo
    RCLONE_CONFIG: "ENCRYPTED[395a61713667b91db33ec7d75b5e30748f06012426c768659c204b80fa29c3061824d882af28f819b489c4a5760416fd]"
    CHAT_ID: "ENCRYPTED[a0761ca8a6d5bb275ba7e87a65a0ffba9e3061848b8be6fff868e4128d5a115e50ba7bae9eb98836bc7eae72e5e7b20d]"
    API_BOT: "ENCRYPTED[0a81f6463d520e317916a3562aa86e5669a3ccb8df59835dc3bbf42f90088148d532d2f5d4605579bb7ee32cc6875830]"

task:
    name: Lineage # Project name
    timeout_in: 120m
    container:
        image: apon77/aosp:latest
        cpu: 8
        memory: 32G
    clone_repo_script:
      - pwd
      - git clone https://github.com/iAboothahir/BuildGo ~/BuildGo
      - chmod -R +x ~/BuildGo
    configure_rclone_script:
      - mkdir -p ~/.config/rclone
      - echo "$RCLONE_CONFIG" > ~/.config/rclone/rclone.conf
    download_ccache_script:
      - cd ~/BuildGo && ./download_ccache
    dumb_script:
      - cd ~/BuildGo && ./dummy_script
    sync_script:
      - cd ~/BuildGo && ./sync_source
    rom_script:
      - cd ~/BuildGo && ./build_rom
    upload_ccache_script:
      - cd ~/BuildGo && ./upload_ccache
     # tmate_script:
     # - cd ~/BuildGo && ./setup_tmate
