#!/bin/bash

CODENAME=laurel_sprout
OUTDIR=out/target/product/$CODENAME
# Normal build steps
cd /tmp/rom
rm device/xiaomi/laurel_sprout/vendorsetup.sh # Yeah I will take care of that here myself
rm -rf vendor/qcom/opensource/commonsys-intf/display && git clone https://github.com/HemantSachdeva/vendor_qcom_opensource_display-commonsys-intf vendor/qcom/opensource/commonsys-intf/display &&
rm -rf vendor/qcom/opensource/wfd-commonsys && git clone https://github.com/HemantSachdeva/vendor_qcom_opensource_wfd-commonsys vendor/qcom/opensource/wfd-commonsys
. build/envsetup.sh
lunch evolution_$CODENAME-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

# Bot Setup
export BOT_MSG_URL="https://api.telegram.org/bot$API_BOT/sendMessage"
export BOT_BUILD_URL="https://api.telegram.org/bot$API_BOT/sendDocument"
TG_USERNAME=@iHemal

send_msg() {
        curl -s -X POST "$BOT_MSG_URL" -d chat_id="$2" \
                -d "parse_mode=html" \
                -d text="$1"
}

send_file() {
        curl -F chat_id=$CHAT_ID -F document=@${1} -F parse_mode=markdown $BOT_BUILD_URL
}

# First builds for testing and to capture ccache
timeout --kill-after=5400 mka bacon -j$(nproc --all)
