#!/bin/bash

cd /tmp

# Compress function with pigz for faster compression
com() {
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache0 1 # Compression level 1, its enough

time rclone copy ccache0.tar.gz aboo:cirrus/ccache/ci2 -P
